services:
  dtsb-learning-place-dev:
    container_name: dtsb_learning_place_dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - '127.0.0.1:3000:3000' # Next.js on port 3000
    volumes:
      - ../:/workspace/app:cached
      - ~/.aws/:/home/vscode/.aws:cached
    tty: true

volumes:
  dtsb-learning-place-dev:
