name: Deploy container image to ECR and static files to S3

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 30
    env:
      ECR_REPOSITORY: production/datatech-learing-place
      ECS_CLUSTER: dtlp_prod_common
      ECS_SERVICE: dtlp_prod_nextjs_app
      S3_STATIC_ASSETS_URI: s3://dtlp-prod-static-assets/_next/

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-northeast-1
          audience: sts.amazonaws.com

      - name: Get dot environment file
        run: |
          aws s3 cp s3://dtlp-prod-secret-files/.env.production.local .env.production.local

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Copy static files from builder
        run: |
          mkdir -p .next/static
          docker cp $(docker create --rm ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest):/app/.next/static .next/static
          
      - name: Upload static files to S3
        run: |
          aws s3 cp .next/static/ ${{ env.S3_STATIC_ASSETS_URI }} --recursive

      - name: Delete dot environment file
        run: |
          rm -f .env.production.local

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment
